name: alnawadi
description: A new Flutter project.



version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.7.0
  easy_localization: ^3.0.2
  flutter_phoenix: ^1.1.1
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_svg: ^2.0.4
  shared_preferences: ^2.0.20
  get_it: ^7.2.0
  go_router: ^9.0.3
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  pin_code_fields: ^8.0.1
  dio: ^5.3.0
  pretty_dio_logger: ^1.3.1
  rxdart: ^0.27.7
  fluttertoast: ^8.2.2
  animate_do: ^3.0.2
  dotted_border: ^2.0.0+3
  connectivity_plus: ^4.0.2
  carousel_slider: ^4.2.1
  easy_stepper: ^0.7.3
  flutter_html: ^3.0.0-beta.2
  firebase_messaging: ^14.6.7
  firebase_core: ^2.15.1
  flutter_local_notifications: ^15.1.1
  flutter_inappwebview: ^5.8.0
  chewie: ^1.7.1
  video_player: ^2.7.2
  video_thumbnail: ^0.5.3





dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.4.6


flutter:

  uses-material-design: true



  assets:
    - assets/images/
    - assets/svg/
    - assets/translations/ar-SA.json
    - assets/translations/en-US.json


  # example:
  fonts:
    - family: vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Thin.ttf
          weight: 100
        - asset: assets/fonts/Vazirmatn-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Vazirmatn-Light.ttf
          weight: 300
        - asset: assets/fonts/Vazirmatn-Regular.ttf
          weight: 400
        - asset: assets/fonts/Vazirmatn-Medium.ttf
          weight: 500
        - asset: assets/fonts/Vazirmatn-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Vazirmatn-Bold.ttf
          weight: 700
        - asset: assets/fonts/Vazirmatn-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Vazirmatn-Black.ttf
          weight: 900